name: znn_controller_dart
description: Zenon Node Controller
version: 0.0.4
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dcli: ^2.1.0
  dart_ipify: ^1.1.1
  system_info2: ^3.0.2
  random_string_generator: ^2.0.0
  znn_sdk_dart:
    git:
      url: https://github.com/zenon-network/znn_sdk_dart.git

dev_dependencies:
  test: ^1.17.9
  lints: ^2.0.1
