name: znn_controller_dart
description: Zenon Node Controller
version: 0.0.3
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dcli: ^1.16.2
  linux_system_info: ^0.0.7
  dart_ipify: ^1.1.1
  random_string_generator: ^2.0.0
  znn_sdk_dart:
    git:
      url: https://github.com/zenon-network/znn_sdk_dart.git

dev_dependencies:
  test: ^1.17.9
  lints: ^1.0.1
